# Generated by Django 3.2.23 on 2024-01-21 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_filter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reply',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.post'),
        ),
    ]
